services:
  mysql:
    image: mysql:8.4
    container_name: payment-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: payment_service_db
    ports:
      - "3309:3306"
    volumes:
      - payment_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ORDER_SERVICE_URL: http://host.docker.internal:8083
    ports:
      - "8084:8084"
    restart: unless-stopped

volumes:
  payment_mysql_data:
